// <auto-generated />
using System;
using EvoDcimManager.Infra.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EvoDcimManager.Infra.Migrations
{
    [DbContext(typeof(ActiveContext))]
    [Migration("20211019135637_AddOtherEntities")]
    partial class AddOtherEntities
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EvoDcimManager.Domain.ActiveContext.Entities.BaseEquipment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Manufactor")
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Model")
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(30)");

                    b.Property<string>("SerialNumber")
                        .HasColumnType("varchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("BaseEquipment");
                });

            modelBuilder.Entity("EvoDcimManager.Domain.ActiveContext.Entities.Rack", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Localization")
                        .HasColumnType("varchar(12)");

                    b.Property<int>("Size")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Rack");
                });

            modelBuilder.Entity("EvoDcimManager.Domain.ActiveContext.Entities.RackEquipment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("BaseEquipmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("FinalPosition")
                        .HasColumnType("int");

                    b.Property<int>("InitialPosition")
                        .HasColumnType("int");

                    b.Property<Guid?>("RackId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("BaseEquipmentId");

                    b.HasIndex("RackId");

                    b.ToTable("RackEquipment");
                });

            modelBuilder.Entity("EvoDcimManager.Domain.ActiveContext.Entities.RackPosition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("EquipmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("FinalPosition")
                        .HasColumnType("int");

                    b.Property<int>("InitialPosition")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EquipmentId");

                    b.ToTable("RackPosition");
                });

            modelBuilder.Entity("EvoDcimManager.Domain.ActiveContext.Entities.Server", b =>
                {
                    b.HasBaseType("EvoDcimManager.Domain.ActiveContext.Entities.RackEquipment");

                    b.Property<string>("Cpu")
                        .HasColumnType("varchar(20)");

                    b.Property<int>("Memory")
                        .HasColumnType("int");

                    b.Property<int>("Storage")
                        .HasColumnType("int");

                    b.ToTable("Server");
                });

            modelBuilder.Entity("EvoDcimManager.Domain.ActiveContext.Entities.Storage", b =>
                {
                    b.HasBaseType("EvoDcimManager.Domain.ActiveContext.Entities.RackEquipment");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.ToTable("Storage");
                });

            modelBuilder.Entity("EvoDcimManager.Domain.ActiveContext.Entities.Switch", b =>
                {
                    b.HasBaseType("EvoDcimManager.Domain.ActiveContext.Entities.RackEquipment");

                    b.Property<int>("EthPorts")
                        .HasColumnType("int");

                    b.ToTable("Switch");
                });

            modelBuilder.Entity("EvoDcimManager.Domain.ActiveContext.Entities.RackEquipment", b =>
                {
                    b.HasOne("EvoDcimManager.Domain.ActiveContext.Entities.BaseEquipment", "BaseEquipment")
                        .WithMany()
                        .HasForeignKey("BaseEquipmentId");

                    b.HasOne("EvoDcimManager.Domain.ActiveContext.Entities.Rack", null)
                        .WithMany("RackEquipments")
                        .HasForeignKey("RackId");

                    b.Navigation("BaseEquipment");
                });

            modelBuilder.Entity("EvoDcimManager.Domain.ActiveContext.Entities.RackPosition", b =>
                {
                    b.HasOne("EvoDcimManager.Domain.ActiveContext.Entities.RackEquipment", "Equipment")
                        .WithMany()
                        .HasForeignKey("EquipmentId");

                    b.Navigation("Equipment");
                });

            modelBuilder.Entity("EvoDcimManager.Domain.ActiveContext.Entities.Server", b =>
                {
                    b.HasOne("EvoDcimManager.Domain.ActiveContext.Entities.RackEquipment", null)
                        .WithOne()
                        .HasForeignKey("EvoDcimManager.Domain.ActiveContext.Entities.Server", "Id")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EvoDcimManager.Domain.ActiveContext.Entities.Storage", b =>
                {
                    b.HasOne("EvoDcimManager.Domain.ActiveContext.Entities.RackEquipment", null)
                        .WithOne()
                        .HasForeignKey("EvoDcimManager.Domain.ActiveContext.Entities.Storage", "Id")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EvoDcimManager.Domain.ActiveContext.Entities.Switch", b =>
                {
                    b.HasOne("EvoDcimManager.Domain.ActiveContext.Entities.RackEquipment", null)
                        .WithOne()
                        .HasForeignKey("EvoDcimManager.Domain.ActiveContext.Entities.Switch", "Id")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EvoDcimManager.Domain.ActiveContext.Entities.Rack", b =>
                {
                    b.Navigation("RackEquipments");
                });
#pragma warning restore 612, 618
        }
    }
}
