// <auto-generated />
using System;
using EvoDcimManager.Infra.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EvoDcimManager.Infra.Migrations
{
    [DbContext(typeof(ActiveContext))]
    partial class ActiveContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EvoDcimManager.Domain.ActiveContext.Entities.Rack", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Localization")
                        .HasMaxLength(12)
                        .HasColumnType("varchar(12)");

                    b.Property<int>("Size")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("rack");
                });

            modelBuilder.Entity("EvoDcimManager.Domain.ActiveContext.Entities.Server", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("RackId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RackId");

                    b.ToTable("server");
                });

            modelBuilder.Entity("EvoDcimManager.Domain.ActiveContext.Entities.Rack", b =>
                {
                    b.OwnsMany("EvoDcimManager.Domain.ActiveContext.ValueObjects.RackPosition", "Slots", b1 =>
                        {
                            b1.Property<Guid>("RackId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<int>("FinalPosition")
                                .HasColumnType("int");

                            b1.Property<int>("InitialPosition")
                                .HasColumnType("int");

                            b1.Property<int>("TempId")
                                .HasColumnType("int");

                            b1.HasKey("RackId", "Id");

                            b1.ToTable("RackPosition");

                            b1.WithOwner()
                                .HasForeignKey("RackId");

                            b1.OwnsOne("EvoDcimManager.Domain.ActiveContext.Entities.RackEquipment", "Equipment", b2 =>
                                {
                                    b2.Property<Guid>("RackPositionRackId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<int>("RackPositionId")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("int")
                                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                                    b2.Property<Guid>("Id")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<Guid?>("RackId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.HasKey("RackPositionRackId", "RackPositionId");

                                    b2.HasIndex("RackId")
                                        .IsUnique()
                                        .HasFilter("[Equipment_RackId] IS NOT NULL");

                                    b2.ToTable("RackPosition");

                                    b2.HasOne("EvoDcimManager.Domain.ActiveContext.Entities.Rack", "Rack")
                                        .WithOne()
                                        .HasForeignKey("EvoDcimManager.Domain.ActiveContext.Entities.RackEquipment", "RackId");

                                    b2.WithOwner()
                                        .HasForeignKey("RackPositionRackId", "RackPositionId");

                                    b2.OwnsOne("EvoDcimManager.Domain.ActiveContext.ValueObjects.BaseEquipment", "BaseEquipment", b3 =>
                                        {
                                            b3.Property<Guid>("RackEquipmentRackPositionRackId")
                                                .HasColumnType("uniqueidentifier");

                                            b3.Property<int>("RackEquipmentRackPositionId")
                                                .ValueGeneratedOnAdd()
                                                .HasColumnType("int")
                                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                                            b3.Property<string>("Manufactor")
                                                .HasMaxLength(30)
                                                .HasColumnType("varchar(30)")
                                                .HasColumnName("Manufactor");

                                            b3.Property<string>("Model")
                                                .HasMaxLength(30)
                                                .HasColumnType("varchar(30)")
                                                .HasColumnName("Model");

                                            b3.Property<string>("Name")
                                                .HasMaxLength(30)
                                                .HasColumnType("varchar(30)")
                                                .HasColumnName("Name");

                                            b3.Property<string>("SerialNumber")
                                                .HasMaxLength(30)
                                                .HasColumnType("varchar(30)")
                                                .HasColumnName("SerialNumber");

                                            b3.HasKey("RackEquipmentRackPositionRackId", "RackEquipmentRackPositionId");

                                            b3.ToTable("RackPosition");

                                            b3.WithOwner()
                                                .HasForeignKey("RackEquipmentRackPositionRackId", "RackEquipmentRackPositionId");
                                        });

                                    b2.Navigation("BaseEquipment");

                                    b2.Navigation("Rack");
                                });

                            b1.Navigation("Equipment");
                        });

                    b.Navigation("Slots");
                });

            modelBuilder.Entity("EvoDcimManager.Domain.ActiveContext.Entities.Server", b =>
                {
                    b.HasOne("EvoDcimManager.Domain.ActiveContext.Entities.Rack", "Rack")
                        .WithMany()
                        .HasForeignKey("RackId");

                    b.OwnsOne("EvoDcimManager.Domain.ActiveContext.ValueObjects.BaseEquipment", "BaseEquipment", b1 =>
                        {
                            b1.Property<Guid>("ServerId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Manufactor")
                                .HasMaxLength(30)
                                .HasColumnType("varchar(30)")
                                .HasColumnName("Manufactor");

                            b1.Property<string>("Model")
                                .HasMaxLength(30)
                                .HasColumnType("varchar(30)")
                                .HasColumnName("Model");

                            b1.Property<string>("Name")
                                .HasMaxLength(30)
                                .HasColumnType("varchar(30)")
                                .HasColumnName("Name");

                            b1.Property<string>("SerialNumber")
                                .HasMaxLength(30)
                                .HasColumnType("varchar(30)")
                                .HasColumnName("SerialNumber");

                            b1.HasKey("ServerId");

                            b1.ToTable("server");

                            b1.WithOwner()
                                .HasForeignKey("ServerId");
                        });

                    b.OwnsOne("EvoDcimManager.Domain.ActiveContext.ValueObjects.Capacity", "Storage", b1 =>
                        {
                            b1.Property<Guid>("ServerId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("TempId1")
                                .HasColumnType("int");

                            b1.Property<int>("Value")
                                .HasColumnType("int")
                                .HasColumnName("Storage");

                            b1.HasKey("ServerId");

                            b1.ToTable("server");

                            b1.WithOwner()
                                .HasForeignKey("ServerId");
                        });

                    b.OwnsOne("EvoDcimManager.Domain.ActiveContext.ValueObjects.Cpu", "Cpu", b1 =>
                        {
                            b1.Property<Guid>("ServerId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Name")
                                .HasMaxLength(30)
                                .HasColumnType("varchar(30)")
                                .HasColumnName("Cpu");

                            b1.Property<int>("TempId1")
                                .HasColumnType("int");

                            b1.HasKey("ServerId");

                            b1.ToTable("server");

                            b1.WithOwner()
                                .HasForeignKey("ServerId");
                        });

                    b.OwnsOne("EvoDcimManager.Domain.ActiveContext.ValueObjects.Memory", "Memory", b1 =>
                        {
                            b1.Property<Guid>("ServerId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("TempId1")
                                .HasColumnType("int");

                            b1.Property<int>("Value")
                                .HasColumnType("int")
                                .HasColumnName("Memory");

                            b1.HasKey("ServerId");

                            b1.ToTable("server");

                            b1.WithOwner()
                                .HasForeignKey("ServerId");
                        });

                    b.Navigation("BaseEquipment");

                    b.Navigation("Cpu");

                    b.Navigation("Memory");

                    b.Navigation("Rack");

                    b.Navigation("Storage");
                });
#pragma warning restore 612, 618
        }
    }
}
